spring:
  application:
    name: client-service

  # Spring Boot 3 + Spring Cloud 2023+: Config Server se configura con spring.config.import.
  # Para desarrollo local, lo hacemos opcional para que el servicio levante aunque el config-server no esté arriba.
  config:
    import: optional:configserver:http://localhost:8081

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: toolrent-backend
            client-secret: 8IYpgVkH76TRaC4E8hEmnGF4r7wL3XgL
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/toolrent-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/toolrent-realm

# Si usas Eureka, configúralo por properties (no necesitas @EnableEurekaClient)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8097