server:
  port: 8080

# Config local de respaldo. Si usas Config Server, puede sobreescribir esto.
# La idea es que el gateway arranque aunque config-server/keycloak no est√©n arriba.
spring:
  application:
    name: gateway-service
  cloud:
    config:
      fail-fast: false

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.security: INFO

