spring:
  application:
    name: loan-service

  config:
    import: optional:configserver:http://localhost:8081

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: toolrent-backend
            client-secret: 8IYpgVkH76TRaC4E8hEmnGF4r7wL3XgL
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/toolrent-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/toolrent-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8098

services:
  tool:
    base-url: http://localhost:8080/TOOL-SERVICE
  client:
    base-url: http://localhost:8080/CLIENT-SERVICE
  kardex:
    base-url: http://localhost:8080/KARDEX-SERVICE
  fine:
    base-url: http://localhost:8080/FINE-SERVICE